//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingRooms
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblTotalGuests;
        protected global::System.Web.UI.WebControls.Label lblTotalReservations;
        protected global::System.Web.UI.WebControls.Label lblActiveBookings;
        protected global::System.Web.UI.WebControls.Label lblAvailableRooms;
        protected global::System.Web.UI.WebControls.GridView gvTodayCheckIns;
        protected global::System.Web.UI.WebControls.GridView gvTodayCheckOuts;
        protected global::System.Web.UI.WebControls.GridView gvRecentReservations;
        protected global::System.Web.UI.WebControls.GridView gvRoomOccupancy;
    }
}
