//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingRooms
{
    public partial class Reservations
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlGuest;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGuest;
        protected global::System.Web.UI.WebControls.DropDownList ddlRoomType;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRoomType;
        protected global::System.Web.UI.WebControls.TextBox txtCheckIn;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCheckIn;
        protected global::System.Web.UI.WebControls.TextBox txtCheckOut;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCheckOut;
        protected global::System.Web.UI.WebControls.CompareValidator cvCheckOut;
        protected global::System.Web.UI.WebControls.TextBox txtAdults;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdults;
        protected global::System.Web.UI.WebControls.RangeValidator rvAdults;
        protected global::System.Web.UI.WebControls.TextBox txtChildren;
        protected global::System.Web.UI.WebControls.RangeValidator rvChildren;
        protected global::System.Web.UI.WebControls.TextBox txtSpecialRequests;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.GridView gvReservations;
        protected global::System.Web.UI.WebControls.Label lblTotalReservations;
        protected global::System.Web.UI.WebControls.Label lblActiveReservations;
        protected global::System.Web.UI.WebControls.Label lblTodayCheckIns;
        protected global::System.Web.UI.WebControls.Label lblTodayCheckOuts;
    }
}
