//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingRooms
{
    public partial class Test
    {
        protected global::System.Web.UI.WebControls.Button btnTestDatabase;
        protected global::System.Web.UI.WebControls.Label lblDatabaseResult;
        protected global::System.Web.UI.WebControls.Label lblServerTime;
        protected global::System.Web.UI.WebControls.Label lblAspNetVersion;
        protected global::System.Web.UI.WebControls.Label lblAppPath;
    }
}
